# TOML language quick introduction
# (Tom's Obvious, Minimal Language)
# If you see a [stuff], that means there is going to be nesting
# If you see [[stuff]], that means it is an array item. See menu items for reference
# weight for menus are 1 based, with 1 being the highest(first) priority


baseURL = 'https://krita.org'
title = 'Digital Painting. Creative Freedom'
theme = 'krita-org-theme' 

defaultContentLanguage = 'en'

[languages]
    [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageDirection =  'ltr'
    title = 'Krita Site'
    flagIconLocation = 'images/language-icons/usa.svg'
    weight = 1
    [languages.en.menu]
        [[languages.en.menu.main]]
            name = 'Features'
            url = '/features'
            weight = 1
        [[languages.en.menu.main]]
            name = 'Download'
            url = '/download'
            weight = 2
        [[languages.en.menu.main]]
            name = 'About'
            url = '/about'
            weight = 3
        [[languages.en.menu.main]]
            name = 'Learn'
            url = 'https://docs.krita.org'
            weight = 4
        [[languages.en.menu.main]]
            name = 'Get Involved'
            url = '/get-involved'
            weight = 5
        [[languages.en.menu.main]]
            name = 'Shop'
            url = '/shop'
            weight = 6


    [languages.fr]
    contentDir = 'content/fr'
    languageName = 'French'
    languageDirection = 'ltr'
    title = 'Krita Site (FR Version)'
    flagIconLocation = 'images/language-icons/france.svg'
    weight = 2
    [languages.fr.menu]
        [[languages.fr.menu.main]]
            name = 'Fonctionnalités'
            url = '/features'
            weight = 1
        [[languages.fr.menu.main]]
            name = 'Téléchargement'
            url = '/download'
            weight = 2
        [[languages.fr.menu.main]]
            name = 'A propos'
            url = '/about'
            weight = 3

